inventory(alphamon,50,50,1).
inventory(froyomon,1000,1000,5).
legendary(betamon).
legendary(icemon).
legendary(oreomon).
lebar(17).
tinggi(22).
player(10,4).
heal(1).
exp(0).
wild(piemon).
wild(nougatmon).
wild(marshmon).
wild(lollimon).
wild(kitmon).
wild(jellymon).
wild(honeymon).
wild(gingermon).
wild(froyomon).
wild(eclairmon).
wild(donutmon).
wild(cupmon).
